app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.home, name="home"),
    path("create-resume", views.create_resume, name="create-resume"),
    path("resume", views.resume, name="resume"),

]

resume/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls", namespace='app')),
    path('account/', include("accounts.urls", namespace='accounts')),
    path('account/', include("django.contrib.auth.urls")),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

</head>

<body style="padding-bottom: 0%;">

    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-wide w3-padding w3-card">
            <a href="#" class="w3-bar-item w3-button"><b>RB</b> Resume</a>
            <!-- Float links to the right. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="{% url 'app:create-resume' %}" class="w3-bar-item w3-button">Create</a>
                <a target="_blank" href="{% url 'app:resume' %}" class="w3-bar-item w3-button">View</a>
                {% if not request.user.is_authenticated %}
                <a href="{% url 'login' %}" class="w3-bar-item w3-button">Login</a>
                {% endif %}
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="w3-bar-item w3-button">Logout</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}

</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<script src="{% static 'script.js' %}">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>

</html>

templates/create-resume.html
{% extends 'base.html' %}

{% block title %}
Create Resume
{% endblock %}


{% block content %}

{% load static %}

<div style="margin-top:50px;">
    <form enctype=" multipart/form-data" action="{% url 'app:create-resume' %}" method="POST">
        {% if form.errors %}
        <div class="alert alert-primary" role="alert">
            error
        </div>
        {% endif %}

        {% csrf_token %}

        <div class="form-group">
            <label for="exampleInputEmail1">{{ form.full_name.label }}</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="Enter Full Name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">{{ form.email.label }}</label>
            <input type="email" class="email-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="name@example.com">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.address.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="Address">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.phone.label }}</label>
            <input type="phonenumber" class="form-control" id="exampleInputPassword1" placeholder="Mobile">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.about_you.label }}</label>
            <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Few words about yourself.">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.education.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="Education details">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.career.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="Career">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_1_start.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_1_start">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_1_end.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_1_end">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_1_details.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="job_1_details">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_2_start.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_2_start">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_2_end.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_2_end">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_2_details.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="job_2_details">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_3_start.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_3_start">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_3_end.label }}</label>
            <input type="Date" class="form-control" id="exampleInputPassword1" placeholder="job_3_end">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.job_3_details.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="job_3_details">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.references.label }}</label>
            <input type="Text" class="form-control" id="exampleInputPassword1" placeholder="references">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{ form.image.label }}</label>
            <input type="file" class="form-control" id="exampleInputPassword1" placeholder="Profile Picture">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home Page
{% endblock %}


{% block content %}

{% load static %}

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;padding-top:50px " id="home">
    <img class="w3-image" src="{% static 'images/header-background.jpg' %}" alt="Architecture" width="1500"
        height="800">
    <div class="w3-display-middle w3-margin-top w3-center">
        <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>RB</b></span> <span
                class="w3-hide-small w3-text-dark-grey">Resume</span></h1>
    </div>
</header>

<!-- Page content 
<div class="w3-content w3-padding" style="max-width:1564px"> </div>
    End page content -->

{% endblock %}